<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProductController;

// Default welcome page route
Route::get('/', function () {
    return view('welcome');
});

// Dashboard route (accessible only for authenticated and verified users)
Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

// Profile management routes (authentication required)
Route::middleware('auth')->group(function () {

    Route::get('/profile', [ProfileController::class, 'edit'])
        ->name('profile.edit'); // Show profile edit form

    Route::patch('/profile', [ProfileController::class, 'update'])
        ->name('profile.update'); // Update profile information

    Route::delete('/profile', [ProfileController::class, 'destroy'])
        ->name('profile.destroy'); // Delete user account
});

// Product routes (authentication required)
Route::middleware(['auth'])->group(function () {

    Route::resource('products', ProductController::class); 
    // Create full CRUD routes for products

    Route::get('products/{id}/audits', 
        [ProductController::class, 'audits']
    )->name('products.audits'); 
    // Show audit history for specific product

});

// Include authentication routes generated by Laravel Breeze
require __DIR__.'/auth.php';
